import { GateFeature, PlanStatus } from '../../types/subscription';

export type FeatureGateDefinition = {
  id: GateFeature;
  label: string;
  freeAvailability: 'yes' | 'limited' | 'preview' | 'no';
  proAvailability: 'yes' | 'fair_use';
  usageMetric?: string;
  userExplanation: string;
  upgradeCopy: string;
  offlineBehaviour: 'allow_cached' | 'block' | 'preview';
  implemented: boolean;
};

export const FEATURE_GATE_REGISTRY: Record<GateFeature, FeatureGateDefinition> = {
  ai_chat: {
    id: 'ai_chat',
    label: 'AI chat',
    freeAvailability: 'limited',
    proAvailability: 'fair_use',
    usageMetric: 'aiMessages',
    userExplanation: 'Daily AI message allowance',
    upgradeCopy: 'Continue chatting with generous fair-use AI on Voxa Pro.',
    offlineBehaviour: 'block',
    implemented: true,
  },
  voice_call: {
    id: 'voice_call',
    label: 'Voice calls',
    freeAvailability: 'limited',
    proAvailability: 'fair_use',
    usageMetric: 'voiceMinutes',
    userExplanation: 'Voice conversation minutes',
    upgradeCopy: 'Voice conversations are limited on Free.',
    offlineBehaviour: 'block',
    implemented: false,
  },
  voice_note: {
    id: 'voice_note',
    label: 'Voice notes',
    freeAvailability: 'limited',
    proAvailability: 'fair_use',
    usageMetric: 'voiceNotes',
    userExplanation: 'Daily voice note allowance',
    upgradeCopy: "You've reached today's free voice-note allowance.",
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  image_upload: {
    id: 'image_upload',
    label: 'Camera analysis',
    freeAvailability: 'limited',
    proAvailability: 'fair_use',
    usageMetric: 'imageUploads',
    userExplanation: 'Daily camera analysis allowance',
    upgradeCopy: 'More camera analysis is included with Voxa Pro.',
    offlineBehaviour: 'block',
    implemented: true,
  },
  video_upload: {
    id: 'video_upload',
    label: 'Video uploads',
    freeAvailability: 'limited',
    proAvailability: 'fair_use',
    usageMetric: 'videoUploads',
    userExplanation: 'Video upload allowance',
    upgradeCopy: 'More video uploads are included with Voxa Pro.',
    offlineBehaviour: 'block',
    implemented: false,
  },
  document_upload: {
    id: 'document_upload',
    label: 'Documents',
    freeAvailability: 'limited',
    proAvailability: 'fair_use',
    usageMetric: 'documents',
    userExplanation: 'Document upload allowance',
    upgradeCopy: 'Document uploads expand with Voxa Pro.',
    offlineBehaviour: 'block',
    implemented: true,
  },
  unlimited_memory: {
    id: 'unlimited_memory',
    label: 'Memories',
    freeAvailability: 'limited',
    proAvailability: 'yes',
    usageMetric: 'memoryCount',
    userExplanation: 'Active memory storage',
    upgradeCopy: 'Save more memories with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  advanced_memory: {
    id: 'advanced_memory',
    label: 'Advanced memory',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Advanced memory retrieval',
    upgradeCopy: 'Advanced memory is included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  pinned_memory: {
    id: 'pinned_memory',
    label: 'Pinned memories',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Permanent pinned memories',
    upgradeCopy: 'Pin permanent memories with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  memory_connections: {
    id: 'memory_connections',
    label: 'Memory connections',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Memory connection graph',
    upgradeCopy: 'Explore memory connections with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  timeline: {
    id: 'timeline',
    label: 'Relationship timeline',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Full relationship timeline',
    upgradeCopy: 'See your full relationship timeline with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  multiple_personalities: {
    id: 'multiple_personalities',
    label: 'Multiple personalities',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Multiple companion personalities',
    upgradeCopy: 'Premium Companion Studio traits are included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  premium_voices: {
    id: 'premium_voices',
    label: 'Premium voices',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Premium voice options',
    upgradeCopy: 'Premium voices are included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  calendar_integration: {
    id: 'calendar_integration',
    label: 'Calendar integration',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Calendar integration',
    upgradeCopy: 'Calendar integration is coming soon for Pro members.',
    offlineBehaviour: 'block',
    implemented: false,
  },
  email_assistant: {
    id: 'email_assistant',
    label: 'Email assistant',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Email assistant',
    upgradeCopy: 'Email assistant is not available yet.',
    offlineBehaviour: 'block',
    implemented: false,
  },
  document_understanding: {
    id: 'document_understanding',
    label: 'Document understanding',
    freeAvailability: 'limited',
    proAvailability: 'fair_use',
    userExplanation: 'Document understanding depth',
    upgradeCopy: 'Deeper document understanding is included with Voxa Pro.',
    offlineBehaviour: 'block',
    implemented: true,
  },
  priority_ai: {
    id: 'priority_ai',
    label: 'Priority AI',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Priority responses when available',
    upgradeCopy: 'Priority responses are included with Voxa Pro.',
    offlineBehaviour: 'block',
    implemented: true,
  },
  unlimited_goals: {
    id: 'unlimited_goals',
    label: 'Goals',
    freeAvailability: 'limited',
    proAvailability: 'yes',
    usageMetric: 'goalCount',
    userExplanation: 'Active goals',
    upgradeCopy: 'Plan more goals with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  unlimited_reminders: {
    id: 'unlimited_reminders',
    label: 'Reminders',
    freeAvailability: 'limited',
    proAvailability: 'yes',
    usageMetric: 'reminderCount',
    userExplanation: 'Active reminders',
    upgradeCopy: 'More reminders are included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  life_os: {
    id: 'life_os',
    label: 'Life OS',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Full Life OS planning tools',
    upgradeCopy: 'Unlock the full Life OS with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  future_self: {
    id: 'future_self',
    label: 'Future Self',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Future Self planning',
    upgradeCopy: 'Future Self is included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  vision_board: {
    id: 'vision_board',
    label: 'Vision Board',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Full Vision Board',
    upgradeCopy: 'Build your full Vision Board with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  bucket_list: {
    id: 'bucket_list',
    label: 'Bucket List',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Full Bucket List',
    upgradeCopy: 'Continue your Bucket List with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  life_book: {
    id: 'life_book',
    label: 'Life Book',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Full Life Book',
    upgradeCopy: 'Continue your full Life Book with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  decision_simulator: {
    id: 'decision_simulator',
    label: 'Decision Simulator',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Decision Simulator',
    upgradeCopy: 'Decision Simulator is included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  debate_mode: {
    id: 'debate_mode',
    label: 'Debate Mode',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Debate Mode',
    upgradeCopy: 'Debate Mode is included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  weekly_letter: {
    id: 'weekly_letter',
    label: 'Weekly Companion Letter',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Full weekly letter',
    upgradeCopy: 'Read your full Weekly Companion Letter with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  mood_insights: {
    id: 'mood_insights',
    label: 'Mood insights',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Advanced mood insights',
    upgradeCopy: 'Advanced Mood Insights are included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  conversation_worlds: {
    id: 'conversation_worlds',
    label: 'Conversation Worlds',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Premium conversation worlds',
    upgradeCopy: 'Premium worlds are included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  coaching_hub: {
    id: 'coaching_hub',
    label: 'Specialist coaching',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Specialist coaching modes',
    upgradeCopy: 'Specialist coaching is included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  dream_journal: {
    id: 'dream_journal',
    label: 'Dream Journal insights',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Dream theme insights',
    upgradeCopy: 'Dream Journal insights are included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  arcade_full: {
    id: 'arcade_full',
    label: 'Arcade statistics',
    freeAvailability: 'limited',
    proAvailability: 'yes',
    userExplanation: 'Full arcade stats and sessions',
    upgradeCopy: 'Full arcade statistics are included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  premium_cosmetics: {
    id: 'premium_cosmetics',
    label: 'Premium cosmetics',
    freeAvailability: 'limited',
    proAvailability: 'yes',
    userExplanation: 'Premium cosmetic collection',
    upgradeCopy: 'Premium cosmetics are included with Voxa Pro.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  sports_intelligence: {
    id: 'sports_intelligence',
    label: 'Sports intelligence',
    freeAvailability: 'preview',
    proAvailability: 'yes',
    userExplanation: 'Advanced sports intelligence',
    upgradeCopy: 'Advanced sports intelligence is included with Voxa Pro when live data is available.',
    offlineBehaviour: 'allow_cached',
    implemented: true,
  },
  exports: {
    id: 'exports',
    label: 'Exports',
    freeAvailability: 'no',
    proAvailability: 'yes',
    userExplanation: 'Data exports',
    upgradeCopy: 'Exports will be available for Pro members when implemented.',
    offlineBehaviour: 'block',
    implemented: false,
  },
};

export function getImplementedProFeatures(): FeatureGateDefinition[] {
  return Object.values(FEATURE_GATE_REGISTRY).filter((gate) => gate.implemented);
}

export function getUpgradeCopy(feature: GateFeature): string {
  return FEATURE_GATE_REGISTRY[feature]?.upgradeCopy ?? 'Upgrade to Voxa Pro to continue.';
}
